##############################################
# config.yml of the AreaShop plugin          #
# This plugin has been created by NLThijs48  #
# Check the server minecraft.go-craft.com    #
# and then the Survival server for a demo    #
##############################################

# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ GENERAL: Options that influence the global state of the plugin                                                             │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
## Chatprefix used for all messages in the chat. Also check the 'greeting' lines in the 'flagProfiles' section, 
## these also contain the prefix and you may want to change those to
chatPrefix: '&2[AreaShop]&r '
## The characters used for the prices of regions, will appear before the number, for the euro character use '%euro%'
moneyCharacter: '$'
## The characters used after a currency number, '%euro%' will become the euro character
moneyCharacterAfter: ''
## How many numbers behind the dot should be shown (2 will make numbers like '8.55', '9.01')
fractionalNumbers: 2
## Set this to true if you want to hide '.0' for a number like '15.0' ('4.50' will still stay '4.50')
hideEmptyFractionalPart: true
## The .yml language file that should be used, provided by this plugin: EN, NL
language: EN
## Enable Schematic saving and restoring in general
enableSchematics: true
## The tags you need to write on the sign to trigger the plugin
signTags:
  ## Tag for adding a rent region
  rent: '[rent]'
  ## Tag for adding a buy region
  buy: '[buy]'
  ## Tag for adding a sign to an existing region
  add: '[as]'
## Enable sending stats to http://mcstats.org/ (Metrics plugin)
sendStats: true
## Use colors when sending messages to console and log files
useColorsInConsole: false
## Post error messages in the console when a command run from the config fails (from the 'runCommands' section for example)
postCommandErrors: true
## Enables / disables debug messages in the console, no need to change
debug: false
## Version of the config, do not change!
version: 2.1.1


# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ RENTING: Options that apply to all rent regions                                                                            │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
## Timeformat to use on the signs, default is like '30-06 14:52', US format: 'MM-dd KK:mm a'
## Search for 'java SimpleDateFormat' for more options and documentation
timeFormatSign: 'dd-MM HH:mm'
## Timeformat used in the chat, default is like '30 june 2014 14:52', US format: 'MMMMMMMMMMMMMMMMM dd yyyy KK:mm a'
## Search for 'java SimpleDateFormat' for more options and documentation
timeFormatChat: 'dd MMMMMMMMMMMMMMMMM yyyy HH:mm'
## Time indicators, used for specifing rent duration on the signs
## Be careful with deleting words, will break signs using those, adding is no problem
minutes: [m, min, mins, minute, minutes, minuten, minuut]
hours: [h, hour, hours, uur, uren]
days: [d, day, days, dag, dagen]
months: [M,  month,  months, maanden, maand]
years: [y, year, years, jaar, jaren]
  
  
# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ PERMISSION GROUPS: Assigned by giving players certain permissions                                                          │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
## Configure the max total regions, max rent regions and max buy regions with different groups (-1 is unlimited)
## Assign a group to players by giving them the permission 'areashop.limits.<group>'
## Every player already has the group 'default' and ops have the unlimited group
## All the groups applied to the player will be checked and only if they all allow an extra region it will be permitted
## Add a 'worlds' or 'groups' list to a group to only count regions from those worlds and/or groups .
## This can be used to get different limits for other worlds or area's.
## Give players permissions globally and not per world! That would break limits when then try renting/buying from within another world
limitGroups:
  default:
    total: 1
    rents: 1
    buys: 1

    
# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ PROFILES: Assigned in general (default.yml), for a group (groups.yml) or individually (<region>.yml)                       │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
## Below is a list of default tags that can be used with all the profiles below.
## If a tag has no value (for example when you use %player% when the region is not rented/bought) then the tag will not get replaced
## %region%         The region name (with correct capitalization)
## %player%         The name of the player that rents/buys the region (with correct capitalization), will not get replaced if no renter/buyer
## %uuid%           The uuid of the player that rents/buys the region, will not get replaced if no renter/buyer
## %price%          The price of the region formatted with the configured characters before and after the number
## %duration%       The duration of a rent region, for example '1 d', '4 minutes' or '2 years'
## %world%          The name of the world that the region is in
## %type%           The type of the region, 'rent' or 'buy'
## %until%          The end time of a rent formatted as configured with 'timeFormatChat'
## %untilshort%     The end time of a rent formatted as configured with 'timeFormatSign'
## %width%          The width of the region (amount of blocks on the x-axis)
## %depth%          The depth of the region (amount of blocks on the z-axis)
## %height%         The height of the region (amount of blocks on the y-axis)
## %timeleft%       The time left on the rent (uses the unit of time that fits best, minutes used from 121 seconds till 120 minutes)
  
## Below are profiles for the signs, you can assign profiles to regions 
## by setting 'general.signProfile' in default.yml, groups or individual regions
signProfiles:
  default:
    ## The following sections can be added for performing certain commands when the sign is clicked:
    ## rightClickPlayer, rightClickConsole, shiftRightClickPlayer, shiftRightClickConsole,
    ## leftClickPlayer, leftClickConsole, shiftLeftClickPlayer, shiftLeftClickConsole
    ## Sections with 'Player' at the end will be run by the clicking player and 'Console' ones from the console
    forrent:
      line1: '&2&l[For Rent]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickPlayer:
      - 'areashop rent %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
    rented:
      line1: '&4&l[Rented]'
      line2: '%region%'
      line3: '%player%'
      line4: '%untilshort%'
      rightClickPlayer:
      - 'areashop rent %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop unrent %region%'
    forsale:
      line1: '&2&l[For Sale]'
      line2: '%region%'
      line3: '%price%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
    sold:
      line1: '&4&l[Sold]'
      line2: '%region%'
      line3: '%player%'
      line4:
      rightClickPlayer:
      - 'areashop buy %region%'
      leftClickPlayer:
      - 'areashop info region %region%'
      shiftRightClickPlayer:
      - 'areashop sell %region%'
## Option to run certain commands when one of these events happen
## Commands at a 'before' section will execute before the region details are changed in the AreaShop system
## and before any other actions occurred (changing signs, saving/loading schematics, etc.),
## the 'after' commands will be run when all changes are done.
## After 'before' or 'after' you can create a list of commands (see example at the created event)
eventCommandProfiles:
  default:
    created:
      before:
      after:
  ##  - "say An AreaShop region has been created: %region%"
    deleted:
      before:
      after:
    rented:
      before:
      after:
    extended:
      before:
      after:
    unrented:
      before:
      after:
    bought:
      before:
      after:
    sold:
      before:
      after:
## For the following events you can specify if you want to restore or save the region to a schematic
## After 'save:' or 'restore:' you enter the name of the file to restore from/to
## If you want your regions all looking the same then you can leave out the %region% part to use the same schematic for all
## Be carefull with these options, it could crash your server or destroy (parts of) your world if used wrong!
## The limit 'maximumBlocks' applies to restoring/saving schematics, be sure your regions are below the limit
schematicProfiles:
  default:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: ''
      restore: ''
    unrented:
      save: ''
      restore: '%type%-%region%'
    bought:
      save: ''
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
## Flag profiles to specify what flags should be set on the WorldGuard regions
## All normal region flags as present in WorldGuard can be used, and also members, owners, priority and parent
## Use 'clear' for members or owners to remove all players. Use '' for a normal flag to reset it.
flagProfiles:
  default:
    forrent:
      members: -%player%
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    rented:
      members: +%player%
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    forsale:
      members: -%player%
      greeting: '%lang:prefix%%lang:greeting-forrent%'
    sold:
      members: +%player%
      greeting: '%lang:prefix%%lang:greeting-forrent%'
        
      
      
 ## TODO
# rentWarningProfiles:
#  default:
#    10:
#      commands: 
#      messages: 
      
      
      
      
  
# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ LIMITS AND TIMINGS: Options for limits and the frequencies for certain functions (be very carefull with these!)            │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
## Setting the 'delay' setting to 0 or lower will prevent the taks from runnning, if you don't use a certain feature you 
## could switch the task off this way.

## Maximum number of blocks to save to or restore from a .schemetic
maximumBlocks: 1000000
## Maximum number of locations the teleport function should check to find a safe spot
maximumTries: 50000
## Timings for saving files that need saving
saving:
  ## Time between saving files that need to be saved (not all files will be saved by default)
  delay: 10
  ## How many regions per tick will be saved
  regionsPerTick: 1
## Timings for rent expiration checking
expiration:
  ## Time between checking if rent regions have been expired (seconds)
  delay: 60
  ## Number of rent regions to check per tick (there are 20 ticks in a second)
  regionsPerTick: 5
## Timings for updating signs and region flags (/as updaterents or /as updatebuys)
update:
  ## Number of regions to update per tick (there are 20 ticks in a second)
  regionsPerTick: 2
## Time between checking if any regions need to be unrented because the player was not online for the specified time period (minutes)
## -1 means never, 1440 is one day, 43200 is one month, 525600 is one year
inactive:
  ## Time between checking if a regions needs to be unrented/sold because of inactivity by the player (minutes)
  delay: 15
  ## Number of rent regions to check per tick (there are 20 ticks in a second)
  regionsPerTick: 5
## Timings for the periodic updating of signs (for timeleft tags etc)
signs:
  ## Time between updates of all signs (seconds)
  delay: 60
  ## Number of regions to update signs for per tick (there are 20 ticks in a second)
  regionsPerTick: 1














