# ╔════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
# ║ default.yml file of the AreaShop plugin created by NLThijs48, Github can be found at https://github.com/NLthijs48/AreaShop.║
# ║ All settings below are default settings and can be overridden by group settings or individual region settings.             ║
# ║ More information and tutorials can be found on the wiki: https://github.com/NLthijs48/AreaShop/wiki                        ║
# ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ GENERAL: Options for all regions.                                                                                          │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘  
general:
  ## Set to true to enable saving/restoring for regions as specified in the profile below, which is specified in the config.
  enableRestore: false
  ## The schematic profile from the 'schematicProfiles' section in the config.
  schematicProfile: 'default'
  ## The event commands profile from the 'eventCommandProfiles' section in the config.
  eventCommandProfile: 'default'
  ## The profile for the format of the sign from the 'signProfiles' section in the config.
  signProfile: 'default'
  ## The profile for the WorldGuard flags from the 'flagProfiles' section in the config.
  flagProfile: 'default'
  ## The y location within the region to start searching for safe teleport spots (x and z will be in the middle of the region).
  ## Possible values: bottom, middle, top, integer.
  teleportLocationY: bottom
  ## If true the teleportation algorithm only allows telportation to inside the region, otherwise it will expand
  ## a cube from the starting point to check for safe spots (then it could end outside of the region).
  teleportIntoRegion: true
  ## Same as above, but then for when you teleport to the sign of a region instead of the region itself.
  teleportToSignIntoRegion: false
  ## Set where the '/as find' command should teleport the player to, set to true for the first sign of the region and set to
  ## false to teleport to the location set by '/as settp' or the default location (if not set).
  findTeleportToSign: true
  ## Restricts the '/as buy' and '/as rent' commands to the world of the region.
  restrictedToWorld: false
  ## Restricts the '/as buy' and '/as rent' commands to the region itself (player needs to be inside).
  restrictedToRegion: false
  ## The UUID of the landlord, this player will receive all money from rents/buys (but not reselling with '/as resell').
  landlord: ''
  ## Name of the landlord, if the landlord UUID setting is not provided then the name will be used instead
  landlordName: ''

# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ RENT: Options for rent regions.                                                                                            │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
rent:
  ## The default price of a rental region.
  price: 1000
  ## The default duration of a rental region, you can find all time indicators in config.yml below the RENTING header.
  duration: '1 day'
  ## The percentage of the rent price you get back if you unrent the region (price of time left will be multiplied by this/100).
  moneyBack: 100
  ## Maximum number of extends a player can do (-1 for infinite, 0 for no extending), if they are at this number then
  ## they are force to let their rent run out (and can rent it again at that point).
  maxExtends: -1
  ## The Maximum time they can have the region rented in advance (use times like '1 day' etc, or 'unlimited' for no limit).
  ## This can prevent players from renting their region for a year, and to ensure they periodically have to extend their rent.
  maxRentTime: 'unlimited'
  ## Automatically unrent the region after the specified time between the last login time of the renter and the current time.
  ## Use times like '1 day' etc, or 'disabled' for never.
  inactiveTimeUntilUnrent: 'disabled'
  ## If a region of a player has less then this time left when he joins the server he will get a notice about his region.
  ## Use '' to disable.
  warningOnLoginTime: '1 day'
  ## The profile for the expiration warnings from the 'expirationWarningProfiles' section in the config.
  expirationWarningProfile: 'default'
  ## If renting the region would go above 'maxRentTIme', then extend to the maximum instead of cancelling the rent.
  extendToFullWhenAboveMaxRentTime: true


# ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
# │ BUY: Options for buy regions.                                                                                              │
# └────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
buy:
  ## The default price of a buy region.
  price: 1000
  ## The percentage of the price you get back if you sell the region.
  moneyBack: 100
  ## Automatically sell the region after the specified number of minutes between the last login time of the buyer and the current time
  ## Use times like '1 day' etc, or 'disabled' for never.
  inactiveTimeUntilSell: 'disabled'