name: AreaShop
main: nl.evolutioncoding.areashop.AreaShop
version: 2.1.5_gorea
depend: [Vault, WorldGuard, WorldEdit]
softdepend: [Multiverse-Core]
author: NLThijs48
website: http://dev.bukkit.org/bukkit-plugins/regionbuyandrent/
commands:
  AreaShop:
    description: For all commands use /as help 
    usage: AreaShop has not started correctly, check the console and correct any errors
    aliases: [as]
permissions:
  areashop.*:
    description: Give access to all commands of AreaShop
    children:
      areashop.help: true
      areashop.createrent: true
      areashop.createbuy: true
      areashop.destroyrent: true
      areashop.destroybuy: true
      areashop.rent: true
      areashop.buy: true
      areashop.unrent: true
      areashop.info: true
      areashop.reload: true
      areashop.setrestore: true
      areashop.setprice: true
      areashop.setduration: true
      areashop.teleport: true
      areashop.teleportall: true
      areashop.setteleportall: true
      areashop.teleportsign: true
      areashop.teleportsignall: true
      areashop.tabcomplete: true
      areashop.setteleportoutsideregion: true
      areashop.find: true
      areashop.groupadd: true
      areashop.groupdel: true
      areashop.grouplist: true
      areashop.groupinfo: true
      areashop.limitbypass: true
      areashop.schematicevents: true
      areashop.addsign: true
      areashop.delsign: true
      areashop.renttimebypass: true
      areashop.me: true
      areashop.resellall: true
      areashop.stopresellall: true
      areashop.addfriendall: true
      areashop.delfriendall: true
      areashop.notifyupdate: true
      areashop.stack: true
  areashop.help:
    description: Allows you to see the help pages
    default: true
  areashop.rent:
    description: Allows you to rent a region
    default: true
  areashop.buy:
    description: Allows you to buy a region
    default: true
  areashop.unrent:
    description: Allows you to unrent a specific region
    default: op
  areashop.unrentown:
    description: Allows you to unrent your own region
    default: true
  areashop.sell:
    description: Allows you to sell a specific region
    default: op
  areashop.sellown:
    description: Allows you to sell your own region
    default: true
  areashop.createrent:
    description: Allows you to set up signs for renting regions
    default: op
  areashop.createbuy:
    description: Allows you to set up signs for buying regions
    default: op
  areashop.destroyrent:
    description: Allows you to break signs used for renting regions
    default: op
  areashop.destroybuy:
    description: Allows you to break signs used for renting regions
    default: op
  areashop.info:
    description: Allows you check the status of regions and players
    default: true
  areashop.reload:
    description: Allows you to reload the config and update all region flags and signs
    default: op
  areashop.setrestore:
    description: Allows you to change the restore settings
    default: op
  areashop.setprice:
    description: Allows you to change the price
    default: op
  areashop.setduration:
    description: Allows you to change the duration of a rent
    default: op
  areashop.teleport:
    description: Teleport to your region
    default: true
  areashop.teleportall:
    description: Teleport to all regions
    default: op
  areashop.teleportsign:
    description: Teleport to signs of regions you own
    default: true
  areashop.teleportsignall:
    description: Teleport to signs of all regions
    default: op
  areashop.teleportfriend:
    description: Teleport to regions where you are added as friend
    default: true
  areashop.teleportfriendsign:
    description: Teleport to the sign of regions where you are added as friend
    default: true
  areashop.setteleport:
    description: Set the teleport spot for your region
    default: true
  areashop.setteleportall:
    description: Set the teleport for other regions
    default: op
  areashop.setteleportoutsideregion:
    description: Set the teleport location outside the WorldGuard region
    default: op
  areashop.tabcomplete:
    description: Allows you to tabcomplete all commands (also where you dont have permission)
    default: op
  areashop.find:
    description: Allows you to teleport to a free region (/as find)
    default: true
  areashop.groupadd:
    description: Allows you to add regions to groups
    default: op
  areashop.groupdel:
    description: Allows you to delete regions from groups
    default: op
  areashop.grouplist:
    description: Allows you to list all the groups currently created
    default: op
  areashop.groupinfo:
    description: Allows you to display information about a group (all members)
    default: op
  areashop.rentextendbypass:
    description: Bypass the extend limit on rents
    default: op
  areashop.limits.default:
    description: Assign limits as set in the 'default' group in the 'limitGroups' section of the config
    default: not op
  areashop.limitbypass:
    description: Bypass the limits for renting/buying regions (how many you can have at the same time)
    default: op
  areashop.schematicevents:
    description: Allows you to trigger schematic events for regions
    default: op
  areashop.addsign:
    description: Allows you to add signs to existing regions
    default: op
  areashop.delsign:
    description: Allows you to delete signs from existing regions
    default: op
  areashop.renttimebypass:
    description: Bypass the maximum rent time you can have in advance
    default: op
  areashop.me:
    description: Allows you to get information about your regions
    default: true
  areashop.setownerrent:
    description: Allows you to set the owner of rent regions
    default: op
  areashop.setownerbuy:
    description: Allows you to set the owner of buy regions
    default: op
  areashop.resell:
    description: Allows you to set your region to sell mode for selling to other players
    default: true
  areashop.resellall:
    description: Allows you to set any region into selling mode
    default: op
  areashop.stopresell:
    description: Allows you to set your region into normal mode if it is in sell mode
    default: true
  areashop.stopresellall:
    description: Allows you to set any region into normal mode if it is in sell mode
    default: op
  areashop.addfriend:
    description: Allows you to add friends to your regions
    default: true
  areashop.addfriendall:
    description: Allows you to add friends to all regions
    default: op
  areashop.delfriend: 
    description: Allows you to delete friends from your regions
    default: true
  areashop.delfriendall: 
    description: Allows you to delete friends from all regions
    default: op
  areashop.notifyupdate:
    description: Will notify this player when an update is available
    default: op
  areashop.linksigns:
    description: Allows you to enter sign linking mode
    default: op
  areashop.stack:
    description: Allows you to create regions and add them to AreaShop like the WorldEdit //stack command
    default: op
  areashop.require:
    description: Allows you to change the requirements for any rent
    default: op